export const USERS_SEEN_REQUEST = "USERS_SEEN_REQUEST";
export const USERS_SEEN_SUCCESS = "USERS_SEEN_SUCCESS";
export const USERS_SEEN_FAIL = "USERS_SEEN_FAIL";

export const USERS_ACCEPTE_REQUEST = "USERS_ACCEPTE_REQUEST";
export const USERS_ACCEPTE_SUCCESS = "USERS_ACCEPTE_SUCCESS";
export const USERS_ACCEPTE_FAIL = "USERS_ACCEPTE_FAIL";

export const USERS_DELETE_REQUEST = "USERS_DELETE_REQUEST";
export const USERS_DELETE_SUCCESS = "USERS_DELETE_SUCCESS";
export const USERS_DELETE_FAIL = "USERS_DELETE_FAIL";

export const USER_REGISTER_OWNER_REQUEST = "USER_REGISTER_OWNER_REQUEST";
export const USER_REGISTER_OWNER_SUCCESS = "USER_REGISTER_OWNER_SUCCESS";
export const USER_REGISTER_OWNER_FAIL = "USER_REGISTER_OWNER_FAIL";