export const OWNER_PROFILE_SEEN_REQUEST = "OWNER_PROFILE_SEEN_REQUEST";
export const OWNER_PROFILE_SEEN_SUCCESS = "OWNER_PROFILE_SEEN_SUCCESS";
export const OWNER_PROFILE_SEEN_FAIL = "OWNER_PROFILE_SEEN_FAIL";

export const OWNER_UPDATE_PIC_REQUEST = "OWNER_UPDATE_PIC_REQUEST";
export const OWNER_UPDATE_PIC_SUCCESS = "OWNER_UPDATE_PIC_SUCCESS";
export const OWNER_UPDATE_PIC_FAIL = "OWNER_UPDATE_PIC_FAIL";

export const OWNER_USER_UPDATE_REQUEST = "OWNER_USER_UPDATE_REQUEST";
export const OWNER_USER_UPDATE_SUCCESS = "OWNER_USER_UPDATE_SUCCESS";
export const OWNER_USER_UPDATE_FAIL = "OWNER_USER_UPDATE_FAIL";

export const OWNER_STADE_SEEN_REQUEST = "OWNER_STADE_SEEN_REQUEST";
export const OWNER_STADE_SEEN_SUCCESS = "OWNER_STADE_SEEN_SUCCESS";
export const OWNER_STADE_SEEN_FAIL = "OWNER_STADE_SEEN_FAIL";

export const OWNER_STADE_ADD_REQUEST = "OWNER_STADE_ADD_REQUEST";
export const OWNER_STADE_ADD_SUCCESS = "OWNER_STADE_ADD_SUCCESS";
export const OWNER_STADE_ADD_FAIL = "OWNER_STADE_ADD_FAIL";

export const OWNER_STADE_DELETE_REQUEST = "OWNER_STADE_DELETE_REQUEST";
export const OWNER_STADE_DELETE_SUCCESS = "OWNER_STADE_DELETE_SUCCESS";
export const OWNER_STADE_DELETE_FAIL = "OWNER_STADE_DELETE_FAIL";

export const OWNER_VILLE_SEEN_REQUEST = "OWNER_VILLE_SEEN_REQUEST";
export const OWNER_VILLE_SEEN_SUCCESS = "OWNER_VILLE_SEEN_SUCCESS";
export const OWNER_VILLE_SEEN_FAIL = "OWNER_VILLE_SEEN_FAIL";

export const EVENT_SEEN_REQUEST = "EVENT_SEEN_REQUEST";
export const EVENT_SEEN_SUCCESS = "EVENT_SEEN_SUCCESS";
export const EVENT_SEEN_FAIL = "EVENT_SEEN_FAIL";