export const OWNER_PROFILE_SEEN_REQUEST = "OWNER_PROFILE_SEEN_REQUEST";
export const OWNER_PROFILE_SEEN_SUCCESS = "OWNER_PROFILE_SEEN_SUCCESS";
export const OWNER_PROFILE_SEEN_FAIL = "OWNER_PROFILE_SEEN_FAIL";

export const OWNER_UPDATE_PIC_REQUEST = "OWNER_UPDATE_PIC_REQUEST";
export const OWNER_UPDATE_PIC_SUCCESS = "OWNER_UPDATE_PIC_SUCCESS";
export const OWNER_UPDATE_PIC_FAIL = "OWNER_UPDATE_PIC_FAIL";

export const OWNER_USER_UPDATE_REQUEST = "OWNER_USER_UPDATE_REQUEST";
export const OWNER_USER_UPDATE_SUCCESS = "OWNER_USER_UPDATE_SUCCESS";
export const OWNER_USER_UPDATE_FAIL = "OWNER_USER_UPDATE_FAIL";