export const USER_PROFILE_SEEN_REQUEST = "USER_PROFILE_SEEN_REQUEST";
export const USER_PROFILE_SEEN_SUCCESS = "USER_PROFILE_SEEN_SUCCESS";
export const USER_PROFILE_SEEN_FAIL = "USER_PROFILE_SEEN_FAIL";

export const USER_UPDATE_PIC_REQUEST = "USER_UPDATE_PIC_REQUEST";
export const USER_UPDATE_PIC_SUCCESS = "USER_UPDATE_PIC_SUCCESS";
export const USER_UPDATE_PIC_FAIL = "USER_UPDATE_PIC_FAIL";

export const USER_USER_UPDATE_REQUEST = "USER_USER_UPDATE_REQUEST";
export const USER_USER_UPDATE_SUCCESS = "USER_USER_UPDATE_SUCCESS";
export const USER_USER_UPDATE_FAIL = "USER_USER_UPDATE_FAIL";

