export const USER_PROFILE_SEEN_REQUEST = "USER_PROFILE_SEEN_REQUEST";
export const USER_PROFILE_SEEN_SUCCESS = "USER_PROFILE_SEEN_SUCCESS";
export const USER_PROFILE_SEEN_FAIL = "USER_PROFILE_SEEN_FAIL";

export const USER_UPDATE_PIC_REQUEST = "USER_UPDATE_PIC_REQUEST";
export const USER_UPDATE_PIC_SUCCESS = "USER_UPDATE_PIC_SUCCESS";
export const USER_UPDATE_PIC_FAIL = "USER_UPDATE_PIC_FAIL";

export const USER_USER_UPDATE_REQUEST = "USER_USER_UPDATE_REQUEST";
export const USER_USER_UPDATE_SUCCESS = "USER_USER_UPDATE_SUCCESS";
export const USER_USER_UPDATE_FAIL = "USER_USER_UPDATE_FAIL";

export const USER_SEEOWNEQUIPE_REQUEST = "USER_SEEOWNEQUIPE_REQUEST";
export const USER_SEEOWNEQUIPE_SUCCESS = "USER_SEEOWNEQUIPE_SUCCESS";
export const USER_SEEOWNEQUIPE_FAIL = "USER_SEEOWNEQUIPE_FAIL";

export const USER_FINDBYID_REQUEST = "USER_FINDBYID_REQUEST";
export const USER_FINDBYID_SUCCESS = "USER_FINDBYID_SUCCESS";
export const USER_FINDBYID_FAIL = "USER_FINDBYID_FAIL";

export const USER_CREATEEQUIPE_REQUEST = "USER_CREATEEQUIPE_REQUEST";
export const USER_CREATEEQUIPE_SUCCESS = "USER_CREATEEQUIPE_SUCCESS";
export const USER_CREATEEQUIPE_FAIL = "USER_CREATEEQUIPE_FAIL";

export const EQUIPE_DELETE_REQUEST = "EQUIPE_DELETE_REQUEST";
export const EQUIPE_DELETE_SUCCESS = "EQUIPE_DELETE_SUCCESS";
export const EQUIPE_DELETE_FAIL = "EQUIPE_DELETE_FAIL";

export const PLAYER_SEARCH_REQUEST = "PLAYER_SEARCH_REQUEST";
export const PLAYER_SEARCH_SUCCESS = "PLAYER_SEARCH_SUCCESS";
export const PLAYER_SEARCH_FAIL = "PLAYER_SEARCH_FAIL";

export const ADD_MEMBRE_REQUEST = "ADD_MEMBRE_REQUEST";
export const ADD_MEMBRE_SUCCESS = "ADD_MEMBRE_SUCCESS";
export const ADD_MEMBRE_FAIL = "ADD_MEMBRE_FAIL";

export const DELETE_USER_FROM_EQUIPE_REQUEST = "DELETE_USER_FROM_EQUIPE_REQUEST";
export const DELETE_USER_FROM_EQUIPE_SUCCESS = "DELETE_USER_FROM_EQUIPE_SUCCESS";
export const DELETE_USER_FROM_EQUIPE_FAIL = "DELETE_USER_FROM_EQUIPE_FAIL";

export const SEARCH_STADE_REQUEST = "SEARCH_STADE_REQUEST";
export const SEARCH_STADE_SUCCESS = "SEARCH_STADE_SUCCESS";
export const SEARCH_STADE_FAIL = "SEARCH_STADE_FAIL";

export const GET_STADE_REQUEST = "GET_STADE_REQUEST";
export const GET_STADE_SUCCESS = "GET_STADE_SUCCESS";
export const GET_STADE_FAIL = "GET_STADE_FAIL";